default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: movie_booking_dev
  username: postgres
  password: Anuj.2000
  host: localhost
  port: 5432
production:
  <<: *default
  database: movie_booking_production
  username: postgres
  password: Anuj.2000
