---
default:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  adapter: postgresql
  database: movie_booking_dev
  encoding: unicode
  host: localhost
  password: Anuj.2000
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432
  username: postgres
production:
  adapter: postgresql
  database: movie_booking_production
  encoding: unicode
  password: Anuj.2000
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
