:scheduler:
  :schedule:
    cancel_underoccupied_shows_job:
      cron: '0 * * * *'
      class: CancelUnderoccupiedShowsJob
    notify_upcoming_movies_job:
      cron: '0 7 * * 4'
      class: NotifyUpcomingMoviesJob
